# Generated by Django 5.1.4 on 2024-12-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0002_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
