# Generated by Django 5.1.4 on 2024-12-15 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0005_remove_quiz_quiz_file_userscore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscore',
            options={'ordering': ['-score']},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='update_at',
        ),
        migrations.AlterUniqueTogether(
            name='userscore',
            unique_together={('user', 'quiz')},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='create_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userscore',
            name='rank',
        ),
    ]
