# Generated by Django 5.1.4 on 2024-12-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0006_alter_userscore_options_remove_quiz_update_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='UserScore',
        ),
    ]
