# Generated by Django 5.1.5 on 2025-01-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0010_quiz_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=6),
        ),
    ]
