# Generated by Django 5.1.5 on 2025-02-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0011_remove_quiz_difficulty_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
